### ISSUE TITLE
Config file not read

### ISSUE THREAD

**Issue by ZikZakFR** [wyhaya/see#3]
When I run this command:
see start -t -c see.yml

I get the error:
Serving path   : /home/TestUser
Serving address: http://0.0.0.0
error: Cannot bind to address: 0.0.0.0:80
Os { code: 13, kind: PermissionDenied, message: "Permission denied" }

see.yml contains:
- server:
    listen: 8080
    root: /home/TestUser/www

**Comment by wyhaya** [comment]
Hi @ZikZakFR 

Quick start:
```bash
see start        # Bind 0.0.0.0:80
see start 8080   # Bind 0.0.0.0:8080
```
Use config:
```bash
see -c see.yml
# Check config
see -t -c see.yml
```

**Comment by ZikZakFR** [comment]
Quick start work fine.
Then I noticed that the default config is supposed to be ~/.see/config.yml
So I created the file there with the content
- server:
 listen: 8080
 root: /home/TestUser/www

And the check config returned:

error: Parsing config file failed
ScanError { mark: Marker { index: 17, line: 2, col: 7 }, info: "while parsing a block collection, did not find expected \'-\' indicator" }

**Comment by wyhaya** [comment]
I think your yml format is incorrect
```yml
# bad
- server:
 listen: 8080
 root: /home/TestUser/www
# good
- server:
    listen: 8080
    root: /home/TestUser/www
```
